import { getDb } from "@/lib/db";
import { TASK_TYPES } from "@/lib/pte/taskTypes";
import { payloadSchemaFor } from "@/lib/pte/schemas";
import { Prisma, TaskType } from "@prisma/client";
import { z } from "zod";

/**
 * Bulk import of practice questions from JSON — the shared path used by the
 * CLI (`npm run content:import`) and the admin bulk-import endpoint.
 *
 * Validates each item against the same payload schema the app uses at runtime,
 * skips titles that already exist, and reports per-item outcomes so a partial
 * batch is actionable rather than silently half-applied.
 */

/** Task types whose prompt is delivered as audio generated by `seed:audio`. */
const AUDIO_TASKS = new Set<TaskType>([
  "REPEAT_SENTENCE",
  "RETELL_LECTURE",
  "ANSWER_SHORT_QUESTION",
  "SUMMARIZE_SPOKEN_TEXT",
  "MCQ_MULTI_L",
  "L_FILL_BLANKS",
  "HIGHLIGHT_SUMMARY",
  "MCQ_SINGLE_L",
  "SELECT_MISSING_WORD",
  "HIGHLIGHT_INCORRECT_WORDS",
  "WRITE_FROM_DICTATION",
]);

export const importItemSchema = z.object({
  taskType: z.enum(TaskType),
  title: z.string().min(1),
  instructions: z.string().optional(),
  /** TTS script for audio tasks; stored in promptText. */
  spoken: z.string().optional(),
  payload: z.unknown(),
  tags: z.array(z.string()).default([]),
  difficulty: z.number().int().min(1).max(3).default(2),
});

export type ImportItem = z.infer<typeof importItemSchema>;

export const importFileSchema = z.object({
  items: z.array(importItemSchema).min(1),
});

export interface ImportOutcome {
  /** Rows actually written. Always 0 for a dry run. */
  created: number;
  /** Items that passed validation — what a dry run would have written. */
  valid: number;
  skipped: { title: string; reason: string }[];
}

export interface ImportOptions {
  /** Validate and report without writing. */
  dryRun?: boolean;
  /** Import even if a question with the same title exists. */
  allowDuplicateTitles?: boolean;
}

export async function importQuestions(
  rawItems: unknown[],
  { dryRun = false, allowDuplicateTitles = false }: ImportOptions = {},
): Promise<ImportOutcome> {
  const skipped: ImportOutcome["skipped"] = [];
  const toCreate: {
    item: ImportItem;
    payload: unknown;
  }[] = [];
  const prisma = await getDb();

  // Title is the dedup key: re-running a generation batch should not double up
  // the bank, and generated titles are descriptive enough to collide meaningfully.
  const existingTitles = new Set(
    (await prisma.question.findMany({ select: { title: true } })).map((q) => q.title),
  );
  const seenInBatch = new Set<string>();

  for (const raw of rawItems) {
    const parsed = importItemSchema.safeParse(raw);
    if (!parsed.success) {
      const title =
        typeof (raw as { title?: unknown })?.title === "string"
          ? (raw as { title: string }).title
          : "(untitled)";
      skipped.push({
        title,
        reason: parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; "),
      });
      continue;
    }
    const item = parsed.data;

    const payloadParsed = payloadSchemaFor(item.taskType).safeParse(item.payload);
    if (!payloadParsed.success) {
      skipped.push({
        title: item.title,
        reason: `invalid payload — ${payloadParsed.error.issues
          .map((i) => `${i.path.join(".")}: ${i.message}`)
          .join("; ")}`,
      });
      continue;
    }

    if (!allowDuplicateTitles && (existingTitles.has(item.title) || seenInBatch.has(item.title))) {
      skipped.push({ title: item.title, reason: "a question with this title already exists" });
      continue;
    }

    if (AUDIO_TASKS.has(item.taskType) && !item.spoken?.trim()) {
      skipped.push({
        title: item.title,
        reason: "audio task has no `spoken` script, so no audio could be generated",
      });
      continue;
    }

    seenInBatch.add(item.title);
    toCreate.push({ item, payload: payloadParsed.data });
  }

  if (dryRun || toCreate.length === 0) {
    return { created: 0, valid: toCreate.length, skipped };
  }

  await prisma.question.createMany({
    data: toCreate.map(({ item, payload }) => ({
      section: TASK_TYPES[item.taskType].section,
      taskType: item.taskType,
      title: item.title,
      instructions: item.instructions ?? null,
      // Audio tasks store the TTS script here; `npm run seed:audio` finds them
      // by (mediaType: "audio", mediaUrl: null) and fills in the recording.
      promptText: item.spoken ?? null,
      mediaType: AUDIO_TASKS.has(item.taskType) ? "audio" : null,
      mediaUrl: null,
      payload: payload as object,
      difficulty: item.difficulty,
      tags: item.tags as Prisma.InputJsonValue,
      isSample: true,
    })),
  });

  return { created: toCreate.length, valid: toCreate.length, skipped };
}
