import type { TaskType } from "@prisma/client";

/**
 * Style-alike SAMPLE content for a PTE practice app. This is original practice
 * material written for this project — NOT official PTE questions, and not
 * affiliated with Pearson. `spoken` holds the script that `npm run seed:audio`
 * turns into audio (via TTS) for listening/speaking-prompt tasks; it is stored
 * in Question.promptText and hidden from the client.
 */
export interface SeedItem {
  taskType: TaskType;
  title: string;
  instructions?: string;
  /** For audio tasks: the script that is spoken (stored as promptText). */
  spoken?: string;
  /** For DESCRIBE_IMAGE: which built-in sample chart to render. */
  image?: number;
  payload: unknown;
  tags?: string[];
}

const opt = (pairs: [string, string][]) => pairs.map(([id, text]) => ({ id, text }));

export const SEED: SeedItem[] = [
  // ── SPEAKING · Read Aloud ────────────────────────────────
  { taskType: "READ_ALOUD", title: "Read Aloud — Urban trees", payload: { text: "Urban trees do more than beautify a city; they cool the air, filter pollutants, and provide habitat for wildlife, making dense neighbourhoods far more liveable." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Scientific method", payload: { text: "The scientific method relies on forming a hypothesis, testing it through controlled experiments, and revising conclusions when the evidence demands it." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Ocean currents", payload: { text: "Ocean currents redistribute heat around the planet, influencing regional climates and shaping the migration patterns of countless marine species." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Digital archives", payload: { text: "Digital archives preserve fragile documents, yet they demand constant maintenance because file formats and storage media rapidly become obsolete." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Renewable energy", payload: { text: "As the cost of solar panels continues to fall, renewable energy is becoming an increasingly practical alternative to fossil fuels in many regions." } },

  // ── SPEAKING · Repeat Sentence (audio) ───────────────────
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Library hours", spoken: "The library extends its opening hours during the examination period.", payload: { sentence: "The library extends its opening hours during the examination period." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Lecture moved", spoken: "Tomorrow's lecture has been moved to the main auditorium.", payload: { sentence: "Tomorrow's lecture has been moved to the main auditorium." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Assignment deadline", spoken: "Please submit your assignment before the end of the week.", payload: { sentence: "Please submit your assignment before the end of the week." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Research seminar", spoken: "The research seminar attracted students from several departments.", payload: { sentence: "The research seminar attracted students from several departments." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Field trip", spoken: "Participants should meet at the entrance before nine o'clock.", payload: { sentence: "Participants should meet at the entrance before nine o'clock." } },

  // ── SPEAKING · Describe Image (image) ────────────────────
  { taskType: "DESCRIBE_IMAGE", title: "Describe Image — Energy sources", image: 1, payload: { keyPoints: ["bar chart of energy sources", "solar is the largest share", "coal is the smallest", "compare the four categories"] } },
  { taskType: "DESCRIBE_IMAGE", title: "Describe Image — Website visitors", image: 2, payload: { keyPoints: ["line chart over six months", "visitors rise steadily", "peak in the final month", "brief dip mid-year"] } },
  { taskType: "DESCRIBE_IMAGE", title: "Describe Image — Budget split", image: 3, payload: { keyPoints: ["categories of spending", "housing is the largest", "savings is modest", "compare proportions"] } },
  { taskType: "DESCRIBE_IMAGE", title: "Describe Image — Rainfall", image: 4, payload: { keyPoints: ["monthly rainfall", "wettest in winter", "driest in summer", "clear seasonal pattern"] } },
  { taskType: "DESCRIBE_IMAGE", title: "Describe Image — Sales by region", image: 5, payload: { keyPoints: ["sales across regions", "north leads", "west trails", "overall differences"] } },

  // ── SPEAKING · Re-tell Lecture (audio) ───────────────────
  { taskType: "RETELL_LECTURE", title: "Re-tell — Bee communication", spoken: "Honeybees communicate the location of food through a remarkable behaviour known as the waggle dance. By varying the angle and duration of the dance, a returning forager tells the rest of the hive both the direction and the distance of a flower patch relative to the sun. This efficient signalling system allows a colony to concentrate its efforts on the richest sources of nectar.", payload: { keyPoints: ["waggle dance", "angle shows direction relative to the sun", "duration shows distance", "colony focuses on best nectar"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Memory consolidation", spoken: "During sleep, the brain replays the experiences of the day, strengthening the neural connections that underlie new memories. This process, called consolidation, transfers information from short-term storage in the hippocampus to more durable networks in the cortex. Studies show that people who sleep after learning retain significantly more than those who stay awake.", payload: { keyPoints: ["sleep replays daily experiences", "consolidation strengthens connections", "hippocampus to cortex", "sleep improves retention"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Coral bleaching", spoken: "Coral reefs owe their colour to tiny algae that live inside them and supply most of their food. When ocean temperatures rise even slightly, the corals expel these algae and turn white, a phenomenon called bleaching. If warm conditions persist, the starved corals eventually die, threatening the vast biodiversity that depends on the reef.", payload: { keyPoints: ["algae give colour and food", "warming causes coral to expel algae", "bleaching turns coral white", "prolonged warmth kills reefs"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — The printing press", spoken: "The invention of the printing press in the fifteenth century dramatically lowered the cost of books and accelerated the spread of ideas across Europe. Literacy expanded beyond the clergy and the wealthy, fuelling scientific exchange and religious reform. Historians often regard it as one of the most consequential technologies in human history.", payload: { keyPoints: ["printing press lowered book costs", "ideas spread across Europe", "literacy expanded", "fuelled science and reform"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Urban heat islands", spoken: "Cities tend to be warmer than the surrounding countryside, an effect known as the urban heat island. Dark roofs and paved surfaces absorb sunlight during the day and release it slowly at night, while a lack of vegetation reduces natural cooling. Planners increasingly use reflective materials and green spaces to counter the problem.", payload: { keyPoints: ["cities warmer than countryside", "dark surfaces absorb heat", "little vegetation reduces cooling", "reflective materials and greenery help"] } },

  // ── SPEAKING · Answer Short Question (audio) ─────────────
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Frozen water", spoken: "What do we call water that has frozen solid?", payload: { question: "What do we call water that has frozen solid?", acceptedAnswers: ["ice"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Star at the centre", spoken: "Which star lies at the centre of our solar system?", payload: { question: "Which star lies at the centre of our solar system?", acceptedAnswers: ["the sun", "sun"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Study of plants", spoken: "What is the scientific study of plants called?", payload: { question: "What is the scientific study of plants called?", acceptedAnswers: ["botany"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Days in a week", spoken: "How many days are there in a week?", payload: { question: "How many days are there in a week?", acceptedAnswers: ["seven", "7"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Person who teaches", spoken: "What do we call a person whose job is to teach students at a university?", payload: { question: "What do we call a person who teaches at a university?", acceptedAnswers: ["lecturer", "professor", "teacher"] } },

  // ── WRITING · Summarize Written Text ─────────────────────
  { taskType: "SUMMARIZE_WRITTEN_TEXT", title: "SWT — Sleep and health", payload: { passage: "Chronic sleep deprivation has been linked to a wide range of health problems, including obesity, weakened immunity, and impaired concentration. Researchers argue that adults consistently underestimate how much sleep they need, treating rest as expendable when work or social demands increase. Public-health campaigns, they suggest, should promote sleep with the same urgency as diet and exercise." } },
  { taskType: "SUMMARIZE_WRITTEN_TEXT", title: "SWT — Remote work", payload: { passage: "The rapid shift to remote work has reshaped how organisations operate. While employees often report greater flexibility and reduced commuting stress, managers worry about weaker collaboration and the blurring of boundaries between work and home. Many companies are now experimenting with hybrid models that attempt to preserve the benefits of both arrangements." } },
  { taskType: "SUMMARIZE_WRITTEN_TEXT", title: "SWT — Plastic pollution", payload: { passage: "Plastic waste accumulates in oceans because it is durable, cheap, and rarely recycled effectively. Once in the water, larger items break into microplastics that enter the food chain and prove almost impossible to remove. Scientists emphasise that reducing production and improving waste management are far more effective than clean-up efforts alone." } },
  { taskType: "SUMMARIZE_WRITTEN_TEXT", title: "SWT — Bilingualism", payload: { passage: "Growing up with two languages was once thought to confuse children, but modern research suggests the opposite. Bilingual individuals tend to show stronger executive control, switching between tasks more efficiently and filtering distractions more effectively. Some studies even indicate that lifelong bilingualism may delay the onset of dementia by several years." } },
  { taskType: "SUMMARIZE_WRITTEN_TEXT", title: "SWT — The gig economy", payload: { passage: "The gig economy offers workers the freedom to choose when and how much they work, an arrangement many find appealing. However, this flexibility often comes without the protections of traditional employment, such as paid leave, pensions, or job security. Policymakers face the difficult task of extending basic safeguards without eliminating the flexibility that makes gig work attractive." } },

  // ── WRITING · Write Essay ────────────────────────────────
  { taskType: "WRITE_ESSAY", title: "Essay — Technology and communication", payload: { prompt: "Some people believe that modern technology has made human communication shallower, while others argue it has brought people closer together. Discuss both views and give your own opinion. Write 200–300 words." } },
  { taskType: "WRITE_ESSAY", title: "Essay — University for everyone", payload: { prompt: "A university education should be free and available to everyone who wishes to study. To what extent do you agree or disagree? Support your position with reasons and examples. Write 200–300 words." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Remote work", payload: { prompt: "Do the advantages of working from home outweigh the disadvantages? Discuss with reference to both employees and employers. Write 200–300 words." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Environmental responsibility", payload: { prompt: "Who should bear the greatest responsibility for reducing pollution: individuals, corporations, or governments? Give reasons for your answer. Write 200–300 words." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Study abroad", payload: { prompt: "Studying abroad benefits students far more than studying in their home country. To what extent do you agree or disagree? Write 200–300 words." } },

  // ── READING · R&W Fill in the Blanks (drag) ──────────────
  { taskType: "RW_FILL_BLANKS", title: "R&W FIB — Coffee", payload: { text: "Coffee is one of the most {{b1}} beverages in the world, {{b2}} by millions of people every day for its stimulating {{b3}}.", blanks: [{ id: "b1", answer: "popular" }, { id: "b2", answer: "consumed" }, { id: "b3", answer: "effects" }], wordBank: ["popular", "consumed", "effects", "rejected", "producing", "flavours"] } },
  { taskType: "RW_FILL_BLANKS", title: "R&W FIB — Museums", payload: { text: "Modern museums increasingly {{b1}} interactive exhibits that {{b2}} visitors to engage directly with the objects on {{b3}}.", blanks: [{ id: "b1", answer: "feature" }, { id: "b2", answer: "encourage" }, { id: "b3", answer: "display" }], wordBank: ["feature", "encourage", "display", "prevent", "avoid", "storage"] } },
  { taskType: "RW_FILL_BLANKS", title: "R&W FIB — Volcanoes", payload: { text: "When a volcano {{b1}}, it can release vast quantities of ash that {{b2}} sunlight and temporarily {{b3}} the surrounding climate.", blanks: [{ id: "b1", answer: "erupts" }, { id: "b2", answer: "block" }, { id: "b3", answer: "cool" }], wordBank: ["erupts", "block", "cool", "freezes", "reflect", "warm"] } },
  { taskType: "RW_FILL_BLANKS", title: "R&W FIB — Exercise", payload: { text: "Regular exercise not only {{b1}} physical health but also {{b2}} mood by triggering the {{b3}} of endorphins.", blanks: [{ id: "b1", answer: "improves" }, { id: "b2", answer: "boosts" }, { id: "b3", answer: "release" }], wordBank: ["improves", "boosts", "release", "reduces", "lowers", "storage"] } },
  { taskType: "RW_FILL_BLANKS", title: "R&W FIB — Migration", payload: { text: "Many birds {{b1}} thousands of kilometres each year, {{b2}} the seasons to find abundant food and suitable {{b3}} sites.", blanks: [{ id: "b1", answer: "migrate" }, { id: "b2", answer: "following" }, { id: "b3", answer: "breeding" }], wordBank: ["migrate", "following", "breeding", "remain", "ignoring", "feeding"] } },

  // ── READING · MCQ single ─────────────────────────────────
  { taskType: "MCQ_SINGLE_R", title: "MCQ (single) — Bees", instructions: "Read the passage and answer the question.", payload: { passage: "Bees are essential pollinators, transferring pollen between flowers and enabling the reproduction of many crops. A decline in bee populations therefore threatens global food security.", question: "What is the main idea of the passage?", options: opt([["a", "Bees are dangerous to crops."], ["b", "Bees play a vital role in pollination and food production."], ["c", "Bees are increasing in number."], ["d", "Bees only pollinate wild flowers."]]), correctOptionId: "b" } },
  { taskType: "MCQ_SINGLE_R", title: "MCQ (single) — Rivers", payload: { passage: "The delta forms where a river deposits sediment as it enters a larger, calmer body of water. Over centuries, these deposits build fertile land that has long attracted human settlement.", question: "Why are deltas often densely settled?", options: opt([["a", "They are rich in sediment and fertile."], ["b", "They are always at high altitude."], ["c", "They never flood."], ["d", "They lack fresh water."]]), correctOptionId: "a" } },
  { taskType: "MCQ_SINGLE_R", title: "MCQ (single) — Antibiotics", payload: { passage: "Overusing antibiotics accelerates the evolution of resistant bacteria, because the drugs kill vulnerable strains and leave hardier ones to multiply.", question: "What does antibiotic overuse encourage?", options: opt([["a", "The extinction of all bacteria."], ["b", "The spread of resistant bacteria."], ["c", "Faster healing in every case."], ["d", "Weaker bacteria only."]]), correctOptionId: "b" } },
  { taskType: "MCQ_SINGLE_R", title: "MCQ (single) — Glaciers", payload: { passage: "Glaciers act as natural reservoirs, storing water as ice in winter and releasing it gradually in summer. Communities downstream rely on this steady flow for agriculture.", question: "What function do glaciers serve for downstream communities?", options: opt([["a", "They block rivers permanently."], ["b", "They provide a steady seasonal water supply."], ["c", "They cause year-round drought."], ["d", "They have no effect on rivers."]]), correctOptionId: "b" } },
  { taskType: "MCQ_SINGLE_R", title: "MCQ (single) — Advertising", payload: { passage: "Advertisers increasingly tailor messages to individuals using data about their browsing habits, a practice that raises clear concerns about privacy.", question: "What concern does targeted advertising raise?", options: opt([["a", "Privacy."], ["b", "Lower prices."], ["c", "Slower internet."], ["d", "Better spelling."]]), correctOptionId: "a" } },

  // ── READING · MCQ multiple ───────────────────────────────
  { taskType: "MCQ_MULTI_R", title: "MCQ (multiple) — Renewable energy", payload: { passage: "Renewable sources such as solar and wind produce little direct pollution and are effectively inexhaustible. However, their output varies with the weather, and building the infrastructure requires significant upfront investment.", question: "Which statements are supported by the passage? (Select all that apply.)", options: opt([["a", "Renewables produce little direct pollution."], ["b", "Renewables are effectively inexhaustible."], ["c", "Renewable output is perfectly constant."], ["d", "Renewables require upfront investment."]]), correctOptionIds: ["a", "b", "d"] } },
  { taskType: "MCQ_MULTI_R", title: "MCQ (multiple) — Reading habits", payload: { passage: "Regular reading expands vocabulary, improves concentration, and exposes readers to diverse perspectives. It does not, however, guarantee academic success on its own.", question: "According to the passage, reading can: (Select all that apply.)", options: opt([["a", "expand vocabulary"], ["b", "improve concentration"], ["c", "guarantee academic success"], ["d", "expose readers to diverse perspectives"]]), correctOptionIds: ["a", "b", "d"] } },
  { taskType: "MCQ_MULTI_R", title: "MCQ (multiple) — Cities", payload: { passage: "Compact cities can reduce car dependence and preserve surrounding farmland. Critics counter that high density may raise housing costs and strain local services.", question: "Which points appear in the passage? (Select all that apply.)", options: opt([["a", "Compact cities can reduce car dependence."], ["b", "Density can raise housing costs."], ["c", "Density always lowers costs."], ["d", "Compact cities can preserve farmland."]]), correctOptionIds: ["a", "b", "d"] } },
  { taskType: "MCQ_MULTI_R", title: "MCQ (multiple) — Volunteering", payload: { passage: "Volunteering builds social connections and can develop practical skills valued by employers. Yet it demands time that some people struggle to spare.", question: "The passage mentions that volunteering: (Select all that apply.)", options: opt([["a", "builds social connections"], ["b", "can develop practical skills"], ["c", "requires no time at all"], ["d", "demands time"]]), correctOptionIds: ["a", "b", "d"] } },
  { taskType: "MCQ_MULTI_R", title: "MCQ (multiple) — Tourism", payload: { passage: "Tourism can boost local economies and fund conservation, but heavy visitor numbers may damage fragile sites and inflate prices for residents.", question: "Which effects of tourism are stated? (Select all that apply.)", options: opt([["a", "boosts local economies"], ["b", "can fund conservation"], ["c", "always lowers resident prices"], ["d", "may damage fragile sites"]]), correctOptionIds: ["a", "b", "d"] } },

  // ── READING · Re-order Paragraphs ────────────────────────
  { taskType: "REORDER_PARAGRAPHS", title: "Re-order — Photosynthesis", payload: { items: opt([["s1", "Photosynthesis is the process by which green plants make their own food."], ["s2", "It begins when chlorophyll in the leaves captures energy from sunlight."], ["s3", "This energy is used to convert carbon dioxide and water into glucose."], ["s4", "The glucose then fuels the plant's growth, while oxygen is released as a by-product."]]), correctOrder: ["s1", "s2", "s3", "s4"] } },
  { taskType: "REORDER_PARAGRAPHS", title: "Re-order — Coffee history", payload: { items: opt([["s1", "According to legend, coffee was discovered by an Ethiopian goat herder."], ["s2", "He noticed that his goats became lively after eating certain berries."], ["s3", "Curious, he tried the berries himself and felt unusually alert."], ["s4", "Word of the energising fruit eventually spread across the Arab world."]]), correctOrder: ["s1", "s2", "s3", "s4"] } },
  { taskType: "REORDER_PARAGRAPHS", title: "Re-order — The experiment", payload: { items: opt([["s1", "The researchers first formulated a clear hypothesis."], ["s2", "They then designed an experiment to test it under controlled conditions."], ["s3", "After collecting the data, they analysed the results statistically."], ["s4", "Finally, they published their conclusions for others to review."]]), correctOrder: ["s1", "s2", "s3", "s4"] } },
  { taskType: "REORDER_PARAGRAPHS", title: "Re-order — Recycling", payload: { items: opt([["s1", "Recycling begins when households sort their waste into separate bins."], ["s2", "Collection trucks then transport the materials to a sorting facility."], ["s3", "There, machines and workers separate paper, glass, and plastics."], ["s4", "The sorted materials are finally processed into new products."]]), correctOrder: ["s1", "s2", "s3", "s4"] } },
  { taskType: "REORDER_PARAGRAPHS", title: "Re-order — Job application", payload: { items: opt([["s1", "The candidate first submitted an application and a tailored résumé."], ["s2", "A recruiter reviewed the documents and shortlisted promising applicants."], ["s3", "Those selected were invited to a series of interviews."], ["s4", "The strongest candidate was then offered the position."]]), correctOrder: ["s1", "s2", "s3", "s4"] } },

  // ── READING · Fill in the Blanks (dropdown) ──────────────
  { taskType: "R_FILL_BLANKS", title: "R FIB — Experiment", payload: { text: "The experiment was {{b1}} under carefully controlled {{b2}}, and the results were {{b3}} recorded for later analysis.", blanks: [{ id: "b1", answer: "conducted", options: ["conducted", "avoided", "ignored"] }, { id: "b2", answer: "conditions", options: ["conditions", "chances", "reasons"] }, { id: "b3", answer: "meticulously", options: ["meticulously", "carelessly", "rarely"] }] } },
  { taskType: "R_FILL_BLANKS", title: "R FIB — Ecosystem", payload: { text: "Every species plays a {{b1}} role in the ecosystem, and the loss of even one can have {{b2}} consequences for the entire {{b3}}.", blanks: [{ id: "b1", answer: "distinct", options: ["distinct", "useless", "random"] }, { id: "b2", answer: "far-reaching", options: ["far-reaching", "trivial", "pleasant"] }, { id: "b3", answer: "community", options: ["community", "machine", "document"] }] } },
  { taskType: "R_FILL_BLANKS", title: "R FIB — Economy", payload: { text: "When interest rates {{b1}}, borrowing becomes more expensive, which tends to {{b2}} consumer spending and slow economic {{b3}}.", blanks: [{ id: "b1", answer: "rise", options: ["rise", "vanish", "sing"] }, { id: "b2", answer: "reduce", options: ["reduce", "increase", "colour"] }, { id: "b3", answer: "growth", options: ["growth", "silence", "weather"] }] } },
  { taskType: "R_FILL_BLANKS", title: "R FIB — Language", payload: { text: "Languages {{b1}} constantly, as new words emerge and old ones fall {{b2}} of use, reflecting changes in the surrounding {{b3}}.", blanks: [{ id: "b1", answer: "evolve", options: ["evolve", "freeze", "shrink"] }, { id: "b2", answer: "out", options: ["out", "in", "over"] }, { id: "b3", answer: "culture", options: ["culture", "machine", "planet"] }] } },
  { taskType: "R_FILL_BLANKS", title: "R FIB — Health", payload: { text: "A balanced diet {{b1}} the body with essential nutrients, helping to {{b2}} illness and maintain overall {{b3}}.", blanks: [{ id: "b1", answer: "provides", options: ["provides", "denies", "hides"] }, { id: "b2", answer: "prevent", options: ["prevent", "cause", "enjoy"] }, { id: "b3", answer: "wellbeing", options: ["wellbeing", "confusion", "furniture"] }] } },

  // ── LISTENING · Summarize Spoken Text (audio) ────────────
  { taskType: "SUMMARIZE_SPOKEN_TEXT", title: "SST — Photosynthesis", spoken: "Photosynthesis is fundamental to life on Earth. Using energy from sunlight, plants convert carbon dioxide and water into glucose, which stores chemical energy, and they release oxygen as a by-product. This single process supplies the food that sustains nearly all ecosystems and produces most of the oxygen we breathe.", payload: { transcript: "Photosynthesis is fundamental to life on Earth. Using energy from sunlight, plants convert carbon dioxide and water into glucose, and release oxygen. It supplies food for ecosystems and most of the oxygen we breathe.", keyPoints: ["plants use sunlight", "convert CO2 and water into glucose", "release oxygen", "sustains ecosystems"] } },
  { taskType: "SUMMARIZE_SPOKEN_TEXT", title: "SST — The internet", spoken: "The internet began as a small research network designed to let computers share data reliably even if part of the system failed. Over decades it grew into a global infrastructure connecting billions of devices. Today it underpins commerce, education, and communication, though it also raises pressing questions about privacy and security.", payload: { transcript: "The internet began as a small research network built to share data reliably. It grew into global infrastructure connecting billions of devices, underpinning commerce, education, and communication, while raising privacy and security concerns.", keyPoints: ["started as research network", "grew globally", "connects billions of devices", "raises privacy and security concerns"] } },
  { taskType: "SUMMARIZE_SPOKEN_TEXT", title: "SST — Vaccines", spoken: "Vaccines work by training the immune system to recognise a specific pathogen without causing the disease itself. They introduce a harmless component of the microbe, prompting the body to produce protective antibodies. If the real pathogen later appears, the immune system responds quickly, preventing serious illness and helping to protect whole communities.", payload: { transcript: "Vaccines train the immune system to recognise a pathogen without causing disease, prompting protective antibodies. If the real pathogen appears, the body responds quickly, preventing serious illness and protecting communities.", keyPoints: ["train the immune system", "harmless component prompts antibodies", "fast response later", "protect communities"] } },
  { taskType: "SUMMARIZE_SPOKEN_TEXT", title: "SST — Sleep", spoken: "Sleep is far from a passive state. While we rest, the brain consolidates memories, clears metabolic waste, and regulates hormones that control appetite and stress. Consistently poor sleep is linked to impaired judgement, weakened immunity, and a higher risk of chronic disease, which is why researchers treat it as a pillar of good health.", payload: { transcript: "Sleep is active: the brain consolidates memories, clears waste, and regulates hormones. Poor sleep impairs judgement, weakens immunity, and raises chronic-disease risk, making it a pillar of health.", keyPoints: ["sleep is active", "consolidates memory and clears waste", "regulates hormones", "poor sleep harms health"] } },
  { taskType: "SUMMARIZE_SPOKEN_TEXT", title: "SST — Deforestation", spoken: "Deforestation has consequences that extend far beyond the loss of trees. Forests store enormous amounts of carbon, so clearing them releases greenhouse gases and accelerates climate change. They also regulate rainfall and shelter a large share of the planet's species, meaning their destruction threatens both climate stability and biodiversity.", payload: { transcript: "Deforestation releases stored carbon and accelerates climate change. Forests also regulate rainfall and shelter many species, so clearing them threatens both climate stability and biodiversity.", keyPoints: ["forests store carbon", "clearing releases greenhouse gases", "forests regulate rainfall", "threatens biodiversity"] } },

  // ── LISTENING · MCQ multiple (audio) ─────────────────────
  { taskType: "MCQ_MULTI_L", title: "L-MCQ (multiple) — Coral reefs", spoken: "Coral reefs support roughly a quarter of all marine species, provide food for coastal communities, and protect shorelines from storms. Yet they are highly sensitive to rising temperatures and ocean acidification.", payload: { question: "According to the recording, coral reefs: (Select all that apply.)", options: opt([["a", "support many marine species"], ["b", "protect shorelines from storms"], ["c", "are unaffected by temperature"], ["d", "are sensitive to acidification"]]), correctOptionIds: ["a", "b", "d"] } },
  { taskType: "MCQ_MULTI_L", title: "L-MCQ (multiple) — Electric cars", spoken: "Electric vehicles produce no tailpipe emissions and are cheaper to run than petrol cars. However, their environmental benefit depends on how the electricity is generated, and battery production remains resource-intensive.", payload: { question: "The speaker states that electric vehicles: (Select all that apply.)", options: opt([["a", "produce no tailpipe emissions"], ["b", "are cheaper to run"], ["c", "always help the environment regardless of electricity"], ["d", "rely on resource-intensive batteries"]]), correctOptionIds: ["a", "b", "d"] } },
  { taskType: "MCQ_MULTI_L", title: "L-MCQ (multiple) — Museums", spoken: "Interactive museum exhibits can deepen engagement, help visitors remember information, and appeal to younger audiences. Some curators caution, though, that spectacle should not replace scholarly accuracy.", payload: { question: "The recording mentions that interactive exhibits: (Select all that apply.)", options: opt([["a", "deepen engagement"], ["b", "help visitors remember"], ["c", "guarantee scholarly accuracy"], ["d", "appeal to younger audiences"]]), correctOptionIds: ["a", "b", "d"] } },
  { taskType: "MCQ_MULTI_L", title: "L-MCQ (multiple) — Exercise", spoken: "Regular physical activity strengthens the heart, improves mood, and supports better sleep. The speaker stresses that consistency matters more than intensity for long-term benefits.", payload: { question: "According to the speaker, regular exercise: (Select all that apply.)", options: opt([["a", "strengthens the heart"], ["b", "improves mood"], ["c", "must always be intense"], ["d", "supports better sleep"]]), correctOptionIds: ["a", "b", "d"] } },
  { taskType: "MCQ_MULTI_L", title: "L-MCQ (multiple) — Libraries", spoken: "Modern libraries lend far more than books; they offer digital resources, community events, and quiet study space. Librarians argue that this broader role makes them more relevant than ever.", payload: { question: "The recording says modern libraries offer: (Select all that apply.)", options: opt([["a", "digital resources"], ["b", "community events"], ["c", "only printed books"], ["d", "quiet study space"]]), correctOptionIds: ["a", "b", "d"] } },

  // ── LISTENING · Fill in the Blanks (audio) ───────────────
  { taskType: "L_FILL_BLANKS", title: "L-FIB — Coral discovery", spoken: "Scientists have recently discovered a new species of coral thriving in unusually deep water.", payload: { text: "Scientists have recently {{b1}} a new {{b2}} of coral thriving in unusually {{b3}} water.", blanks: [{ id: "b1", answer: "discovered" }, { id: "b2", answer: "species" }, { id: "b3", answer: "deep" }] } },
  { taskType: "L_FILL_BLANKS", title: "L-FIB — Lecture attendance", spoken: "The lecture attracted a large audience because the topic was both timely and controversial.", payload: { text: "The lecture attracted a large {{b1}} because the topic was both {{b2}} and {{b3}}.", blanks: [{ id: "b1", answer: "audience" }, { id: "b2", answer: "timely" }, { id: "b3", answer: "controversial" }] } },
  { taskType: "L_FILL_BLANKS", title: "L-FIB — Research funding", spoken: "The government announced additional funding to support research into renewable energy technologies.", payload: { text: "The government announced additional {{b1}} to support {{b2}} into renewable {{b3}} technologies.", blanks: [{ id: "b1", answer: "funding" }, { id: "b2", answer: "research" }, { id: "b3", answer: "energy" }] } },
  { taskType: "L_FILL_BLANKS", title: "L-FIB — Ancient trade", spoken: "Ancient traders travelled vast distances to exchange spices, silk, and precious metals.", payload: { text: "Ancient traders travelled vast {{b1}} to exchange spices, {{b2}}, and precious {{b3}}.", blanks: [{ id: "b1", answer: "distances" }, { id: "b2", answer: "silk" }, { id: "b3", answer: "metals" }] } },
  { taskType: "L_FILL_BLANKS", title: "L-FIB — Climate report", spoken: "The report warned that rising temperatures could threaten crops across several continents.", payload: { text: "The report {{b1}} that rising {{b2}} could threaten {{b3}} across several continents.", blanks: [{ id: "b1", answer: "warned" }, { id: "b2", answer: "temperatures" }, { id: "b3", answer: "crops" }] } },

  // ── LISTENING · Highlight Correct Summary (audio) ────────
  { taskType: "HIGHLIGHT_SUMMARY", title: "HCS — Renewable energy", spoken: "The speaker explains that although renewable energy sources like wind and solar are clean and increasingly affordable, their variable output means that reliable storage and backup are essential for a stable grid.", payload: { options: opt([["a", "Renewables are clean and cheaper, but their variable output makes storage and backup essential for a stable grid."], ["b", "Renewables are too expensive and should be abandoned in favour of coal."], ["c", "Wind and solar produce constant output and never need backup."], ["d", "The speaker argues that energy storage is unnecessary."]]), correctOptionId: "a" } },
  { taskType: "HIGHLIGHT_SUMMARY", title: "HCS — Reading", spoken: "The talk emphasises that regular reading widens vocabulary and improves focus, but the speaker notes it is a support for learning rather than a guarantee of success by itself.", payload: { options: opt([["a", "Reading widens vocabulary and improves focus, supporting learning without guaranteeing success alone."], ["b", "Reading has no measurable benefits."], ["c", "Reading alone guarantees academic success."], ["d", "The speaker discourages reading."]]), correctOptionId: "a" } },
  { taskType: "HIGHLIGHT_SUMMARY", title: "HCS — Urbanisation", spoken: "According to the recording, compact cities can cut car use and protect farmland, yet the speaker acknowledges that higher density may push up housing costs and strain services.", payload: { options: opt([["a", "Compact cities cut car use and protect farmland but may raise housing costs and strain services."], ["b", "Compact cities always lower housing costs."], ["c", "The speaker opposes all city growth."], ["d", "Density has no effect on services."]]), correctOptionId: "a" } },
  { taskType: "HIGHLIGHT_SUMMARY", title: "HCS — Sleep", spoken: "The lecturer describes sleep as an active process during which the brain consolidates memories and clears waste, warning that chronic sleep loss harms both mind and body.", payload: { options: opt([["a", "Sleep is an active process that consolidates memory and clears waste; chronic loss harms mind and body."], ["b", "Sleep is a purely passive, unimportant state."], ["c", "The lecturer says sleep loss has no effect."], ["d", "Sleep only affects mood, nothing else."]]), correctOptionId: "a" } },
  { taskType: "HIGHLIGHT_SUMMARY", title: "HCS — Tourism", spoken: "The speaker notes that tourism can fund conservation and boost local economies, but warns that excessive visitor numbers can damage fragile sites and raise living costs for residents.", payload: { options: opt([["a", "Tourism can fund conservation and boost economies, but too many visitors can damage sites and raise costs."], ["b", "Tourism has only negative effects."], ["c", "Tourism never affects local prices."], ["d", "The speaker says fragile sites are indestructible."]]), correctOptionId: "a" } },

  // ── LISTENING · MCQ single (audio) ───────────────────────
  { taskType: "MCQ_SINGLE_L", title: "L-MCQ (single) — Main idea", spoken: "In this segment, the speaker argues that the single most effective way for individuals to reduce their carbon footprint is to change how often they fly, since air travel is remarkably carbon-intensive.", payload: { question: "What is the speaker's main point?", options: opt([["a", "Flying less is a highly effective way to cut one's carbon footprint."], ["b", "Air travel has no climate impact."], ["c", "Individuals cannot affect emissions."], ["d", "Cars are the only source of emissions."]]), correctOptionId: "a" } },
  { taskType: "MCQ_SINGLE_L", title: "L-MCQ (single) — Purpose", spoken: "The presenter introduces a new campus recycling scheme, explaining where the new bins are located and which materials each one accepts.", payload: { question: "What is the purpose of the talk?", options: opt([["a", "To explain a new campus recycling scheme."], ["b", "To announce exam results."], ["c", "To advertise a concert."], ["d", "To describe a sports event."]]), correctOptionId: "a" } },
  { taskType: "MCQ_SINGLE_L", title: "L-MCQ (single) — Detail", spoken: "The researcher reports that the study followed participants for ten years, making it one of the longest investigations of its kind.", payload: { question: "How long did the study last?", options: opt([["a", "Ten years."], ["b", "Ten weeks."], ["c", "One year."], ["d", "Six months."]]), correctOptionId: "a" } },
  { taskType: "MCQ_SINGLE_L", title: "L-MCQ (single) — Attitude", spoken: "While acknowledging the risks of artificial intelligence, the speaker remains broadly optimistic that careful regulation can allow society to enjoy its benefits.", payload: { question: "What is the speaker's attitude toward AI?", options: opt([["a", "Cautiously optimistic."], ["b", "Completely dismissive."], ["c", "Entirely fearful."], ["d", "Uninterested."]]), correctOptionId: "a" } },
  { taskType: "MCQ_SINGLE_L", title: "L-MCQ (single) — Conclusion", spoken: "The lecturer concludes that, above all, consistent daily practice matters far more than occasional bursts of intense effort when learning a language.", payload: { question: "What does the lecturer conclude about language learning?", options: opt([["a", "Consistent daily practice matters most."], ["b", "Only intensive bursts work."], ["c", "Practice is unnecessary."], ["d", "Grammar is the only thing that matters."]]), correctOptionId: "a" } },

  // ── LISTENING · Select Missing Word (audio) ──────────────
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Ecosystem", spoken: "Every species, however small, contributes to the stability of its", payload: { options: opt([["a", "ecosystem"], ["b", "economy"], ["c", "vocabulary"], ["d", "furniture"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Experiment", spoken: "Before drawing any conclusions, the scientists repeated the", payload: { options: opt([["a", "experiment"], ["b", "holiday"], ["c", "sandwich"], ["d", "melody"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Climate", spoken: "Rising sea levels are one of the clearest signs of a changing", payload: { options: opt([["a", "climate"], ["b", "recipe"], ["c", "wardrobe"], ["d", "grammar"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Education", spoken: "Access to quality education can transform the future of an entire", payload: { options: opt([["a", "community"], ["b", "refrigerator"], ["c", "melody"], ["d", "staircase"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Technology", spoken: "Smartphones have completely changed the way people", payload: { options: opt([["a", "communicate"], ["b", "hibernate"], ["c", "photosynthesise"], ["d", "evaporate"]]), correctOptionId: "a" } },

  // ── LISTENING · Highlight Incorrect Words (audio) ────────
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Migration", spoken: "Many birds migrate thousands of kilometres each year to find food and suitable breeding sites.", payload: { transcriptWords: ["Many", "birds", "migrate", "thousands", "of", "kilograms", "each", "year", "to", "find", "food", "and", "suitable", "feeding", "sites."], incorrectIndices: [5, 13] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Library", spoken: "The library extends its opening hours during the examination period every semester.", payload: { transcriptWords: ["The", "library", "extends", "its", "closing", "hours", "during", "the", "examination", "period", "every", "semester."], incorrectIndices: [4] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Photosynthesis", spoken: "Plants use sunlight to convert carbon dioxide and water into glucose and oxygen.", payload: { transcriptWords: ["Plants", "use", "moonlight", "to", "convert", "carbon", "dioxide", "and", "water", "into", "glucose", "and", "nitrogen."], incorrectIndices: [2, 12] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Economy", spoken: "When interest rates rise, borrowing becomes more expensive and spending usually falls.", payload: { transcriptWords: ["When", "interest", "rates", "fall,", "borrowing", "becomes", "more", "expensive", "and", "spending", "usually", "rises."], incorrectIndices: [3, 11] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Vaccines", spoken: "Vaccines train the immune system to recognise a pathogen without causing the disease.", payload: { transcriptWords: ["Vaccines", "train", "the", "immune", "system", "to", "ignore", "a", "pathogen", "without", "causing", "the", "disease."], incorrectIndices: [6] } },

  // ── LISTENING · Write from Dictation (audio) ─────────────
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Lecture start", spoken: "The lecture will begin promptly at noon in the main hall.", payload: { referenceText: "The lecture will begin promptly at noon in the main hall." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Assignments", spoken: "Students must submit their assignments before the deadline on Friday.", payload: { referenceText: "Students must submit their assignments before the deadline on Friday." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Research", spoken: "The research team published its findings in a leading scientific journal.", payload: { referenceText: "The research team published its findings in a leading scientific journal." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Laboratory", spoken: "Access to the laboratory is restricted to authorised personnel only.", payload: { referenceText: "Access to the laboratory is restricted to authorised personnel only." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Enrolment", spoken: "The university offers a wide range of undergraduate and postgraduate courses.", payload: { referenceText: "The university offers a wide range of undergraduate and postgraduate courses." } },
];
