import type { SeedItem } from "./seed-data";

/**
 * Additional hand-authored sample questions, bringing the short-form task types
 * from 5 to 15 each so repetition isn't noticeable out of the box.
 *
 * Passage-heavy types (reading comprehension, gap-fill, re-order, the listening
 * MCQs) are deliberately left at their original 5 here — they need 120–180 word
 * passages each, which is what `npm run content:generate` exists to produce at
 * volume. See README → "Growing the question bank".
 *
 * Original style-alike practice material. Not official PTE content, and not
 * affiliated with Pearson.
 */

const opt = (pairs: [string, string][]) => pairs.map(([id, text]) => ({ id, text }));

export const SEED_EXTRA: SeedItem[] = [
  // ── SPEAKING · Read Aloud ────────────────────────────────
  { taskType: "READ_ALOUD", title: "Read Aloud — Antibiotic resistance", payload: { text: "The overuse of antibiotics in both medicine and agriculture has accelerated the emergence of resistant bacteria, a development that public health researchers describe as one of the most serious long-term threats to modern healthcare." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Museum collections", payload: { text: "Curators must balance the competing demands of preservation and access, since every hour a fragile manuscript spends on public display slightly shortens the lifespan of the very object visitors have come to admire." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Volcanic ash", payload: { text: "When a volcano erupts violently, it can inject vast quantities of ash and sulphur dioxide into the stratosphere, temporarily cooling the global climate by reflecting a portion of incoming sunlight back into space." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Bilingual education", payload: { text: "Children raised in bilingual households often demonstrate greater cognitive flexibility than their monolingual peers, though researchers continue to debate how much of this advantage persists into adulthood." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Antarctic research", payload: { text: "Scientists working at Antarctic research stations endure months of isolation and darkness in order to collect ice cores that preserve a detailed atmospheric record stretching back hundreds of thousands of years." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Urban transport", payload: { text: "Cities that invest heavily in cycling infrastructure typically see a marked reduction in short car journeys, easing congestion and improving air quality without the expense of building new roads." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Behavioural economics", payload: { text: "Behavioural economists have shown that people frequently make decisions which contradict their own stated preferences, particularly when a choice is presented under time pressure or framed in terms of potential losses." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Soil degradation", payload: { text: "Intensive farming can strip soil of organic matter far faster than natural processes replace it, and once fertility declines, restoring the land often takes decades of careful and expensive management." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Peer review", payload: { text: "Although peer review remains the principal safeguard of scientific quality, critics point out that it is slow, largely unpaid, and surprisingly inconsistent in identifying errors within complex statistical analyses." } },
  { taskType: "READ_ALOUD", title: "Read Aloud — Ancient trade routes", payload: { text: "The overland routes linking Asia and the Mediterranean carried not only silk and spices but also technologies, religions and diseases, reshaping the societies at both ends far more profoundly than any single commodity." } },

  // ── SPEAKING · Repeat Sentence (audio) ───────────────────
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Tutorial groups", spoken: "Tutorial groups will be limited to twelve students this term.", payload: { sentence: "Tutorial groups will be limited to twelve students this term." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Reading list", spoken: "The reading list is available on the departmental website.", payload: { sentence: "The reading list is available on the departmental website." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Laboratory safety", spoken: "Protective eyewear must be worn at all times in the laboratory.", payload: { sentence: "Protective eyewear must be worn at all times in the laboratory." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Conference booking", spoken: "Delegates should register online before the end of the month.", payload: { sentence: "Delegates should register online before the end of the month." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Exam results", spoken: "Results will be published two weeks after the final examination.", payload: { sentence: "Results will be published two weeks after the final examination." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Campus parking", spoken: "Parking permits are issued only to postgraduate research students.", payload: { sentence: "Parking permits are issued only to postgraduate research students." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Guest speaker", spoken: "A visiting professor will give the opening lecture on Monday.", payload: { sentence: "A visiting professor will give the opening lecture on Monday." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Group project", spoken: "Each group must nominate one member to present the findings.", payload: { sentence: "Each group must nominate one member to present the findings." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Library fines", spoken: "Overdue books incur a small daily charge until they are returned.", payload: { sentence: "Overdue books incur a small daily charge until they are returned." } },
  { taskType: "REPEAT_SENTENCE", title: "Repeat — Field research", spoken: "The survey data were collected over three consecutive summers.", payload: { sentence: "The survey data were collected over three consecutive summers." } },

  // ── SPEAKING · Answer Short Question (audio) ─────────────
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Instrument for time", spoken: "What instrument do people commonly use to measure time?", payload: { question: "What instrument do people commonly use to measure time?", acceptedAnswers: ["clock", "watch", "a clock", "a watch"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Study of the past", spoken: "What do we call the academic study of past events?", payload: { question: "What do we call the academic study of past events?", acceptedAnswers: ["history"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Frozen dessert", spoken: "If you freeze water in a tray, what do you get?", payload: { question: "If you freeze water in a tray, what do you get?", acceptedAnswers: ["ice", "ice cubes"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Building for books", spoken: "Where would you normally go to borrow a book?", payload: { question: "Where would you normally go to borrow a book?", acceptedAnswers: ["library", "a library", "the library"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Months in a year", spoken: "How many months are there in a year?", payload: { question: "How many months are there in a year?", acceptedAnswers: ["twelve", "12"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Treats animals", spoken: "What do we call a doctor who treats animals?", payload: { question: "What do we call a doctor who treats animals?", acceptedAnswers: ["vet", "veterinarian", "a vet"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Colour of chlorophyll", spoken: "What colour are most healthy leaves?", payload: { question: "What colour are most healthy leaves?", acceptedAnswers: ["green"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Draws buildings", spoken: "What do we call a person who designs buildings?", payload: { question: "What do we call a person who designs buildings?", acceptedAnswers: ["architect", "an architect"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Largest ocean creature", spoken: "What is the name of the largest animal living in the ocean?", payload: { question: "What is the largest animal living in the ocean?", acceptedAnswers: ["blue whale", "whale", "the blue whale"] } },
  { taskType: "ANSWER_SHORT_QUESTION", title: "ASQ — Where you post a letter", spoken: "Where do you take a letter if you want to post it?", payload: { question: "Where do you take a letter if you want to post it?", acceptedAnswers: ["post office", "the post office", "postbox", "mailbox"] } },

  // ── WRITING · Write Essay ────────────────────────────────
  { taskType: "WRITE_ESSAY", title: "Essay — Remote work and collaboration", payload: { prompt: "Some people believe that widespread remote working benefits both employees and society, while others argue it weakens collaboration and isolates workers. Discuss both views and give your own opinion." } },
  { taskType: "WRITE_ESSAY", title: "Essay — University fees", payload: { prompt: "Some argue that university education should be free for all students, while others believe those who benefit financially should contribute to its cost. Discuss both positions and state your view." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Artificial intelligence at work", payload: { prompt: "Artificial intelligence is increasingly used to make decisions in hiring, lending and healthcare. Do the efficiency gains justify reducing human judgement in these areas? Give reasons for your answer." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Car-free city centres", payload: { prompt: "Several cities have banned private cars from their centres to reduce pollution. Some see this as essential progress; others regard it as unfair to residents and small businesses. Discuss both views and give your opinion." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Space exploration spending", payload: { prompt: "Governments spend large sums on space exploration while significant problems remain unsolved on Earth. To what extent do you think this spending is justified?" } },
  { taskType: "WRITE_ESSAY", title: "Essay — Social media and news", payload: { prompt: "An increasing number of people get their news primarily from social media. Does this development do more to inform the public or to mislead it? Support your position with reasons and examples." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Compulsory volunteering", payload: { prompt: "Some countries require secondary school students to complete a period of community service before graduating. Discuss the advantages and disadvantages of making volunteering compulsory, and give your own view." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Preserving minority languages", payload: { prompt: "Many minority languages are disappearing. Some argue that public money should be spent preserving them; others believe resources are better directed elsewhere. Discuss both views and give your opinion." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Four-day working week", payload: { prompt: "Several organisations have trialled a four-day working week without reducing pay. Do you think this model should be adopted more widely? Give reasons for your answer." } },
  { taskType: "WRITE_ESSAY", title: "Essay — Tourism and heritage", payload: { prompt: "Mass tourism brings income to historic cities but also damages the sites visitors come to see. To what extent should access to fragile heritage sites be restricted?" } },

  // ── SPEAKING · Re-tell Lecture (audio) ───────────────────
  { taskType: "RETELL_LECTURE", title: "Re-tell — Antibiotic resistance", spoken: "Bacteria reproduce quickly, and each generation carries small genetic variations. When antibiotics are used heavily, the few bacteria that happen to survive pass on their resistance, and within a short time the resistant strain dominates. This is why doctors are now urged to prescribe antibiotics only when they are genuinely necessary, and why patients are told to finish the entire course.", payload: { keyPoints: ["bacteria reproduce fast with genetic variation", "heavy antibiotic use selects for survivors", "resistant strains come to dominate", "prescribe sparingly and finish the course"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Ice cores", spoken: "Ice sheets build up one snowfall at a time, and each layer traps tiny bubbles of the atmosphere as it existed that year. By drilling deep cores and analysing those bubbles, researchers can reconstruct temperature and carbon dioxide levels going back hundreds of thousands of years. This record is what allows us to say with confidence that current concentrations are unusual.", payload: { keyPoints: ["ice forms in annual layers", "bubbles trap ancient atmosphere", "cores reveal past temperature and CO2", "shows current levels are unusual"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — The placebo effect", spoken: "In clinical trials, some patients given an inactive treatment nevertheless improve, an outcome known as the placebo effect. Expectation appears to trigger real physiological changes, including the release of the body's own painkillers. Because of this, any credible drug trial must compare the new treatment against a placebo rather than against no treatment at all.", payload: { keyPoints: ["inactive treatment can still produce improvement", "expectation causes real physiological change", "body releases its own painkillers", "trials must compare against placebo"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Language acquisition", spoken: "Young children acquire their first language without formal instruction, absorbing complex grammatical rules simply by being surrounded by speech. This ability appears to be strongest in early childhood and declines gradually through adolescence. Linguists disagree about whether this reflects a dedicated biological window or simply the greater time and motivation children devote to listening.", payload: { keyPoints: ["children learn language without instruction", "grammar absorbed from exposure", "ability declines after early childhood", "debate over biological window versus exposure"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Supply and demand", spoken: "When the price of a good rises, producers generally supply more of it while consumers buy less. The point at which these two tendencies balance is called the equilibrium price. Real markets rarely sit exactly at equilibrium, but the model remains useful because it predicts the direction in which prices will move after a shock.", payload: { keyPoints: ["higher prices increase supply", "higher prices reduce demand", "balance point is the equilibrium price", "model predicts direction of price movement"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Plate tectonics", spoken: "The Earth's outer shell is broken into rigid plates that drift slowly over the hotter, softer rock beneath. Where plates pull apart, new crust forms; where they collide, one may be forced beneath the other, building mountain ranges and triggering earthquakes. This single framework explains phenomena that once seemed entirely unrelated.", payload: { keyPoints: ["outer shell divided into drifting plates", "new crust forms where plates separate", "collisions build mountains and cause earthquakes", "unifies previously unrelated phenomena"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Cognitive bias", spoken: "People tend to seek out information that confirms what they already believe, a tendency psychologists call confirmation bias. It operates largely below conscious awareness, which is precisely what makes it difficult to correct. Deliberately seeking evidence that would disprove your position is one of the few strategies shown to reduce its influence.", payload: { keyPoints: ["people favour information confirming existing beliefs", "known as confirmation bias", "operates unconsciously and resists correction", "actively seeking disconfirming evidence helps"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Vaccination and herd immunity", spoken: "When a sufficiently large proportion of a population is immune to a disease, the pathogen struggles to find new hosts and transmission slows dramatically. This indirect protection, known as herd immunity, shields those who cannot be vaccinated, such as newborns and people with compromised immune systems. The threshold required depends on how contagious the disease is.", payload: { keyPoints: ["high immunity slows transmission", "called herd immunity", "protects those who cannot be vaccinated", "threshold depends on contagiousness"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Industrial revolution", spoken: "The shift from hand production to mechanised factories transformed not just manufacturing but the shape of society itself. Populations moved rapidly from the countryside into rapidly expanding cities, family structures changed, and entirely new social classes emerged. Living standards eventually rose substantially, though for the first generations conditions were often extremely harsh.", payload: { keyPoints: ["mechanisation replaced hand production", "rapid migration to cities", "new social classes emerged", "harsh conditions before living standards rose"] } },
  { taskType: "RETELL_LECTURE", title: "Re-tell — Biodiversity and stability", spoken: "Ecosystems containing many different species tend to withstand disturbance better than simplified ones. If several species perform a similar role, the loss of one can be absorbed because others continue the function. This redundancy is one reason ecologists argue that protecting biodiversity is a practical matter of resilience, not merely an aesthetic preference.", payload: { keyPoints: ["diverse ecosystems resist disturbance better", "overlapping roles provide redundancy", "loss of one species can be absorbed", "biodiversity supports practical resilience"] } },

  // ── LISTENING · Select Missing Word (audio) ──────────────
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Manuscripts", spoken: "To protect fragile documents from light damage, archivists store them in controlled", payload: { options: opt([["a", "darkness"], ["b", "laughter"], ["c", "recipes"], ["d", "footwear"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Hypothesis", spoken: "No matter how elegant a theory appears, it must ultimately be tested against", payload: { options: opt([["a", "evidence"], ["b", "furniture"], ["c", "rainfall"], ["d", "applause"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Migration", spoken: "Each autumn these birds travel south, guided by the position of the", payload: { options: opt([["a", "sun"], ["b", "sofa"], ["c", "invoice"], ["d", "keyboard"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Public health", spoken: "Clean drinking water remains one of the most effective ways to prevent", payload: { options: opt([["a", "disease"], ["b", "poetry"], ["c", "furniture"], ["d", "sunshine"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Archaeology", spoken: "By dating the charcoal found at the site, researchers established its approximate", payload: { options: opt([["a", "age"], ["b", "flavour"], ["c", "volume"], ["d", "melody"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Peer review", spoken: "Before a paper appears in a reputable journal, it is examined by independent", payload: { options: opt([["a", "reviewers"], ["b", "vegetables"], ["c", "staircases"], ["d", "thunderstorms"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Soil", spoken: "Earthworms improve fertility by breaking down organic matter within the", payload: { options: opt([["a", "soil"], ["b", "curtain"], ["c", "orchestra"], ["d", "envelope"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Bilingualism", spoken: "Children exposed to two languages from birth often become fluent in", payload: { options: opt([["a", "both"], ["b", "neither"], ["c", "gravity"], ["d", "wallpaper"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Renewable capacity", spoken: "As manufacturing costs continue to fall, installations of solar panels keep on", payload: { options: opt([["a", "rising"], ["b", "melting"], ["c", "singing"], ["d", "sleeping"]]), correctOptionId: "a" } },
  { taskType: "SELECT_MISSING_WORD", title: "SMW — Urban planning", spoken: "Adding parks and reflective roofing helps cities cope with extreme", payload: { options: opt([["a", "heat"], ["b", "grammar"], ["c", "cutlery"], ["d", "biography"]]), correctOptionId: "a" } },

  // ── LISTENING · Highlight Incorrect Words (audio) ────────
  // `spoken` is the correct text that gets read aloud; `transcriptWords` is the
  // altered version shown on screen, with the changed positions listed.
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Committee", spoken: "The committee approved the proposal after a lengthy discussion last Tuesday.", payload: { transcriptWords: ["The", "committee", "rejected", "the", "proposal", "after", "a", "lengthy", "discussion", "last", "Tuesday."], incorrectIndices: [2] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Exercise", spoken: "Regular exercise improves cardiovascular health and reduces the risk of chronic disease.", payload: { transcriptWords: ["Regular", "exercise", "improves", "cardiovascular", "health", "and", "increases", "the", "risk", "of", "chronic", "disease."], incorrectIndices: [6] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Museum", spoken: "The museum houses an extensive collection of ancient manuscripts and rare maps.", payload: { transcriptWords: ["The", "museum", "houses", "an", "extensive", "collection", "of", "modern", "manuscripts", "and", "rare", "maps."], incorrectIndices: [7] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Volcanoes", spoken: "Volcanic eruptions can release enormous quantities of ash into the upper atmosphere.", payload: { transcriptWords: ["Volcanic", "eruptions", "can", "release", "enormous", "quantities", "of", "ash", "into", "the", "lower", "atmosphere."], incorrectIndices: [10] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Antibiotics", spoken: "Antibiotics are ineffective against viral infections such as the common cold.", payload: { transcriptWords: ["Antibiotics", "are", "effective", "against", "viral", "infections", "such", "as", "the", "common", "cold."], incorrectIndices: [2] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Survey", spoken: "The survey found that most respondents preferred flexible working arrangements.", payload: { transcriptWords: ["The", "survey", "found", "that", "few", "respondents", "preferred", "flexible", "working", "arrangements."], incorrectIndices: [4] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Glaciers", spoken: "Glaciers have retreated significantly over the past century in most mountain ranges.", payload: { transcriptWords: ["Glaciers", "have", "advanced", "significantly", "over", "the", "past", "century", "in", "most", "mountain", "ranges."], incorrectIndices: [2] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Industrialisation", spoken: "The author argues that industrialisation fundamentally altered rural communities.", payload: { transcriptWords: ["The", "author", "argues", "that", "industrialisation", "fundamentally", "preserved", "rural", "communities."], incorrectIndices: [6] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Nursing", spoken: "Nurses play a central role in monitoring patients and coordinating their treatment.", payload: { transcriptWords: ["Nurses", "play", "a", "minor", "role", "in", "monitoring", "patients", "and", "coordinating", "their", "treatment."], incorrectIndices: [3] } },
  { taskType: "HIGHLIGHT_INCORRECT_WORDS", title: "HIW — Renewables", spoken: "Renewable sources now generate a substantial proportion of the nation's electricity.", payload: { transcriptWords: ["Renewable", "sources", "now", "generate", "a", "negligible", "proportion", "of", "the", "nation's", "electricity."], incorrectIndices: [5] } },

  // ── LISTENING · Write from Dictation (audio) ─────────────
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Seminar room", spoken: "The seminar has been relocated to the room next to the library.", payload: { referenceText: "The seminar has been relocated to the room next to the library." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Course materials", spoken: "All course materials are now available in electronic format.", payload: { referenceText: "All course materials are now available in electronic format." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Committee meeting", spoken: "The committee will review the applications at its next meeting.", payload: { referenceText: "The committee will review the applications at its next meeting." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Statistical analysis", spoken: "Statistical analysis revealed a significant difference between the groups.", payload: { referenceText: "Statistical analysis revealed a significant difference between the groups." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Field work", spoken: "Students conducting field work must obtain approval from their supervisor.", payload: { referenceText: "Students conducting field work must obtain approval from their supervisor." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Scholarship", spoken: "The scholarship covers tuition fees for the entire academic year.", payload: { referenceText: "The scholarship covers tuition fees for the entire academic year." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Attendance", spoken: "Attendance at the introductory workshop is strongly recommended.", payload: { referenceText: "Attendance at the introductory workshop is strongly recommended." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Manuscript", spoken: "The manuscript was submitted for publication earlier this year.", payload: { referenceText: "The manuscript was submitted for publication earlier this year." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Equipment", spoken: "Laboratory equipment should be returned to the storage cupboard.", payload: { referenceText: "Laboratory equipment should be returned to the storage cupboard." } },
  { taskType: "WRITE_FROM_DICTATION", title: "WFD — Conclusions", spoken: "These conclusions are based on evidence gathered over several decades.", payload: { referenceText: "These conclusions are based on evidence gathered over several decades." } },
];
